var data = {
    "publications":
    [
        // {
        //     "highlight": true,
        //     "img": "",
        //     "title": "",
        //     "authors": "",
        //     "conference": "",
        //     "year": ,
        //     "arxiv": "",
        //     "github": "",
        // },
        {
            "title": "Combining Generative and Geometry Priors for Wide-Angle Portrait Correction",
            "authors": "Lan Yao, Chaofeng Chen, Xiaoming Li, Zifei Yan, Wangmeng Zuo",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
        },
        {
            "title": "ClearCLIP: Decomposing CLIP Representations for Dense Vision-Language Inference",
            "authors": "Mengcheng Lan, Chaofeng Chen, Yiping Ke, Xinjiang Wang, Litong Feng, Wayne Zhang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
        },
        {
            "title": "ProxyCLIP: Proxy Attention Improves CLIP for Open-Vocabulary Segmentation",
            "authors": "Mengcheng Lan, Chaofeng Chen, Yiping Ke, Xinjiang Wang, Litong Feng, Wayne Zhang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
        },

        {
            // "highlight": true,
            "img": "images/ECCV2024_CoInstruct.png",
            "title": "Towards Open-ended Visual Quality Comparison",
            "authors": "Haoning Wu*, Hanwei Zhu*, Zicheng Zhang*, Erli Zhang, Chaofeng Chen, Liang Liao, Chunyi Li, Annan Wang, Wenxiu Sun, Qiong Yan, Xiaohong Liu, Guangtao Zhai, Shiqi Wang, Weisi Lin",
            "conference": "International Conference on Machine Learning (<b>ICML</b>)", 
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2402.16641",
            "github": "https://github.com/Q-Future/Co-Instruct",
        },
        {
            "highlight": true,
            "img": "images/arXiv2023_texforce.jpg",
            "title": "Enhancing Diffusion Models with Text-Encoder Reinforcement Learning",
            "authors": "Chaofeng Chen*, Annan Wang*, Haoning Wu, Liang Liao, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2311.15657",
            "github": "https://github.com/chaofengc/TexForce",
        },
        {
            // "highlight": true,
            "img": "images/onescorer.png",
            "title": "Q-Align: Teaching LMMs for Visual Scoring via Discrete Text-Defined Levels",
            "authors": "Haoning Wu*, Zicheng Zhang*, Weixia Zhang, Chaofeng Chen, Liang Liao, Chunyi Li, Yixuan Gao, Annan Wang, Erli Zhang, Wenxiu Sun, Qiong Yan, Xiongkuo Min, Guangtao Zhai, Weisi Lin",
            "conference": "International Conference on Machine Learning (<b>ICML</b>)", 
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2312.17090",
            "github": "https://github.com/Q-Future/Q-Align",
        },
        // Conference papers
        {
            "title": "Local Distortion Aware Efficient Transformer Adaptation for Image Quality Assessment",
            "authors": "Kangmin Xu, Liang Liao, Jing Xiao, Chaofeng Chen, Haoning Wu, Qiong Yan, Weisi Lin",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2308.12001",
        },
        {
            // "highlight": true,
            "img": "images/qinstruct.jpg",
            "title": "Q-Instruct: Improving Low-level Visual Abilities for Multi-modality Foundation Models",
            "authors": "Haoning Wu*, Zicheng Zhang*, Erli Zhang*, Chaofeng Chen, Liang Liao, Annan Wang, Kaixin Xu, Chunyi Li, Jingwen Hou, Guangtao Zhai, Geng Xue, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2024,
            "arxiv": "https://arxiv.org/abs/2311.06783",
            "github": "https://github.com/Q-Future/Q-Instruct",
        },
        {
            "highlight": true,
            "img": "images/qbench.png",
            "title": "Q-Bench: A Benchmark for General-Purpose Foundation Models on Low-level Vision",
            "authors": "Haoning Wu*, Zicheng Zhang*, Erli Zhang*, Chaofeng Chen, Liang Liao, Annan Wang, Chunyi Li, Wenxiu Sun, Qiong Yan, Guangtao Zhai, Weisi Lin",
            "conference": "International Conference on Learning Representations (<b>ICLR</b>)",
            "oral": "Spotlight",
            "year": "2024",
            "arxiv": "https://arxiv.org/abs/2309.14181",
            "github": "https://github.com/Q-Future/Q-Bench",
        },
        {
            "highlight": true,
            "img": "images/AAAI2024_ITER.jpg",
            "title": "Iterative Token Evaluation and Refinement for Real-World Super-Resolution",
            "authors": "Chaofeng Chen, Shangchen Zhou, Liang Liao, Haoning Wu, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "Association for the Advancement of Artificial Intelligence (<b>AAAI</b>)",
            "year": "2024",
            "arxiv": "https://arxiv.org/abs/2312.05616",
            "github": "https://github.com/chaofengc/ITER",
        },
        {
            "img": "",
            "title": "Towards Explainable In-the-wild Video Quality Assessment: A Database and a Language-Prompted Approach",
            "authors": "Haoning Wu*, Erli Zhang*, Liang Liao, Chaofeng Chen, Jingwen Hou, Annan Wang, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "ACM Multimedia (<b>MM</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2305.12726",
            "github": "https://github.com/VQAssessment/ExplainableVQA",
            "oral": "Oral",
        },
        {
            // "highlight": true,
            "img": "images/ICCV2023_DOVER.png",
            "title": "Exploring Video Quality Assessment on User Generated Contents from Aesthetic and Technical Perspectives",
            "authors": "Haoning Wu*, Erli Zhang*, Liang Liao*, Chaofeng Chen, Jingwen Hou, Annan Wang, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "International Conference on Computer Vision (<b>ICCV</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2211.04894",
            "github": "https://github.com/VQAssessment/DOVER",
        },
        {
            // "highlight": true,
            "img": "images/ICME2023_buona_vista.png",
            "title": "Exploring Opinion-Unaware Video Quality Assessment with Semantic Affinity Criterion",
            "authors": "Haoning Wu, Liang Liao, Jingwen Hou, Chaofeng Chen, Erli Zhang, Annan Wang, Wenxiu Sun, Qiong Yan, and Weisi Lin",
            "conference": "IEEE International Conference on Multimedia and Expo (<b>ICME</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2302.13269",
            "github": "https://github.com/VQAssessment/BVQI",
        },
        {
            // "highlight": true,
            "img": "images/AAAI2023_MIMO.png",
            "title": "MIMO Is All You Need: A Strong Multi-In-Multi-Out Baseline for Video Prediction",
            "authors": "Shuliang Ning*, Mengcheng Lan*, Yanran Li, Chaofeng Chen, Qian Chen, Xunlai Chen, Xiaoguang Han, Shuguang Cui",
            "conference": "Association for the Advancement of Artificial Intelligence (<b>AAAI</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2212.04655",
            "github": "https://github.com/ningshuliang/MIMO-VP",
        },
        {
            // "highlight": true,
            "img": "",
            "title": "S3-NeRF: Neural Reflectance Field from Shading and Shadow under a Single Viewpoint",
            "authors": "Wenqi Yang, Guanying Chen, Chaofeng Chen, Zhenfang Chen, Kwan-Yee K. Wong",
            "conference": "Conference on Neural Information Processing Systems (<b>NeurIPS</b>)",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2210.08936",
            "github": "https://github.com/ywq/s3nerf",
            "project": "https://ywq.github.io/s3nerf/",
        },
        {
            // "highlight": true,
            // "img": "images/ECCV2022_fastvqa.gif",
            "title": "FAST-VQA: Efficient End-to-end Video Quality Assessment with Fragment Sampling",
            "authors": "Haoning Wu, Chaofeng Chen, Jingwen Hou, Liang Liao, Annan Wang, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2207.02595",
            "github": "https://github.com/VQAssessment/FAST-VQA-and-FasterVQA",
        },

        {
            // "highlight": true,
            "img": "images/ECCV2022_ReDegNet.jpg",
            "title": "From Face to Natural Image: Learning Real Degradation for Blind Image Super-Resolution",
            "authors": "Xiaoming Li, Chaofeng Chen, Xianhui Lin, Wangmeng Zuo, Lei Zhang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2210.00752",
            "github": "https://github.com/csxmli2016/ReDegNet",
        },
        {
            "highlight": true,
            "img": "images/MM2022_FeMaSR.jpg",
            "title": "Real-World Blind Super-Resolution via Feature Matching with Implicit High-Resolution Priors",
            "authors": "Chaofeng Chen*, Xinyu Shi*, Yipeng Qin, Xiaoming Li, Xiaoguang Han, Tao Yang, Shihui Guo",
            "conference": "ACM Multimedia (<b>MM</b>)",
            "oral": "Oral",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2202.13142",
            "github": "https://github.com/chaofengc/FeMaSR",
        },
        {
            // "highlight": true,
            "img": "images/MM2022_TPQI.jpg",
            "title": "Exploring the Effectiveness of Video Perceptual Representation in Blind Video Quality Assessment",
            "authors": "Liang Liao, Kangmin Xu, Haoning Wu, Chaofeng Chen, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "conference": "ACM Multimedia (<b>MM</b>)",
            "oral": "Oral",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2207.03723",
            "github": "https://github.com/UoLMM/TPQI-VQA",
        },
        {
            // "highlight": true,
            "img": "",
            "title": "A Unified Framework for Masked and Mask-Free Face Recognition via Feature Rectification",
            "authors": "Shaozhe Hao, Chaofeng Chen, Zhenfang Chen, Kwan-Yee K. Wong",
            "conference": "International Conference on Image Processing (<b>ICIP</b>)",
            "year": "2022",
            "arxiv": "https://arxiv.org/abs/2202.07358",
            "github": "https://github.com/haoosz/FFR-Net",
        },
        {
            // "highlight": true,
            "img": "images/ICCV2021_HDRNet.jpg",
            "title": "HDR Video Reconstruction: A Coarse-to-fine Network and A Real-world Benchmark Dataset",
            "authors": "Guanying Chen, Chaofeng Chen, Shi Guo, Zhetong Liang, Kwan-Yee K. Wong, Lei Zhang",
            "conference": "International Conference on Computer Vision (<b>ICCV</b>)",
            "year": "2021",
            "arxiv": "https://arxiv.org/abs/2103.14943",
            "github": "https://github.com/guanyingc/DeepHDRVideo",
            "project": "https://guanyingc.github.io/DeepHDRVideo/",
        },
        {
            "highlight": true,
            "img": "images/PSFR-GAN.jpg",
            "title": "Progressive Semantic-Aware Style Transformation for Blind Face Restoration",
            "authors": "Chaofeng Chen, Xiaoming Li, Lingbo Yang, Xianhui Lin, Lei Zhang, Kwan-Yee K. Wong",
            "conference": "Computer Vision and Pattern Recognition (<b>CVPR</b>)",
            "year": 2021,
            "arxiv": "https://arxiv.org/abs/2009.08709",
            "github": "https://github.com/chaofengc/PSFRGAN",
        },
        {
            "highlight": true,
            "img": "images/ECCV2020_dfdnet.jpg",
            "title": "Blind Face Restoration via Deep Multi-scale Component Dictionaries",
            "authors": "Xiaoming Li, Chaofeng Chen, Shangchen Zhou, Xianhui Lin, Wangmeng Zuo, Lei Zhang",
            "conference": "European Conference on Computer Vision (<b>ECCV</b>)",
            "year": "2020",
            "arxiv": "https://arxiv.org/abs/2008.00418",
            "github": "https://github.com/csxmli2016/DFDNet",
        },
        {
            // "highlight": true,
            "img": "images/ACCV2018_face_sketch_wild.png",
            "title": "Semi-Supervised Learning for Face Sketch Synthesis in the Wild",
            "authors": "Chaofeng Chen, Wei Liu, Xiao Tan, Kwan-Yee K. Wong",
            "conference": "Asia Conference on Computer Vision (<b>ACCV</b>)",
            "year": "2018",
            "arxiv": "https://arxiv.org/abs/1812.04929",
            "github": "https://github.com/chaofengc/Face-Sketch-Wild",
        },
        {
            // "highlight": true,
            "img": "images/ACCV2018_scale_aware_ocr.png",
            "title": "SAFE: Scale Aware Feature Encoder for Scene Text Recognition",
            "authors": "Wei Liu, Chaofeng Chen, Kwan-Yee K. Wong",
            "conference": "Asia Conference on Computer Vision (<b>ACCV</b>)",
            "year": "2018",
            "arxiv": "https://arxiv.org/abs/1901.05770",
        },
        {
            // "highlight": true,
            "img": "images/WACV2018_face_sketch_pcf.png",
            "title": "Face Sketch Synthesis with Style Transfer using Pyramid Column Feature",
            "authors": "Chaofeng Chen*, Xiao Tan*, Kwan-Yee K. Wong",
            "conference": "IEEE Winter Conference on Applications of Computer Vision (<b>WACV</b>)",
            "year": "2018",
            "arxiv": "https://arxiv.org/abs/2009.08679",
            "github": "https://github.com/chaofengc/Face-Sketch",
        },
        {
            // "highlight": true,
            "img": "images/AAAI2018_char_net.png",
            "title": "Char-Net: A Character-Aware Neural Network for Distorted Scene Text Recognition",
            "authors": "Wei Liu, Chaofeng Chen, Kwan-Yee K. Wong ",
            "conference": "AAAI Conference on Artificial Intelligence (<b>AAAI</b>)",
            "oral": "Oral",
            "year": "2018",
            "pdf": "http://www.visionlab.cs.hku.hk/publications/wliu_aaai18.pdf",
        },
        {
            // "highlight": true,
            "img": "images/BMVC2016_star_net.png",
            "title": "STAR-Net: A SpaTial Attention Residue Network for Scene Text Recognition.",
            "authors": "Wei Liu, Chaofeng Chen, Kwan-Yee K. Wong, Z. Su and J. Han",
            "conference": "British Machine Vision Conference (<b>BMVC</b>)",
            "year": "2016",
            "pdf": "http://www.visionlab.cs.hku.hk/publications/wliu_bmvc16.pdf",
            // "github": "",
        },
        // ========================================
        // Journal papers
        // ========================================
        {
            "highlight": true,
            "img": "images/arXiv2023_topiq.png",
            "title": "TOPIQ: A Top-down Approach from Semantics to Distortions for Image Quality Assessment",
            "authors": "Chaofeng Chen, Jiadi Mo, Jingwen Hou, Haoning Wu, Liang Liao, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": "2024",
            "arxiv": "https://arxiv.org/abs/2308.03060",
            "github": "https://github.com/chaofengc/IQA-PyTorch",
        },
        {
            "title": "Towards Transparent Deep Image Aesthetics Assessment with Tag-based Content Descriptors",
            "authors": "Jingwen Hou, Weisi Lin, Yuming Fang, Haoning Wu, Chaofeng Chen, Liang Liao, Weide Liu",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": "2023",
            "pdf": "https://ieeexplore.ieee.org/abstract/document/10235894"
        },
        {
            "highlight": true,
            "img": "images/TPAMI2023_FastVQA.jpg",
            "title": "Neighbourhood Representative Sampling for Efficient End-to-end Video Quality Assessment",
            "authors": "Haoning Wu, Chaofeng Chen, Liang Liao, Jingwen Hou, Wenxiu Sun, Qiong Yan, Jinwei Gu, Weisi Lin",
            "journal": "IEEE Transactions on Pattern Analysis and Machine Intelligence (<b>TPAMI</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2210.05357",
            "github": "https://github.com/timothyhtimothy/FAST-VQA-and-FasterVQA",
        },
        {
            // "highlight": true,
            "img": "images/CVIU2023_FaceSCG.png",
            "title": "Semi-supervised Cycle-GAN for face photo-sketch translation in the wild",
            "authors": "Chaofeng Chen, Wei Liu, Xiao Tan, Kwan-Yee K. Wong",
            "journal": "Computer Vision and Image Understanding (<b>CVIU</b>)",
            "year": "2023 (<b>ACCV extension</b>)",
            "arxiv": "https://arxiv.org/abs/2307.10281",
            "github": "https://github.com/chaofengc/Face-Sketch-SCG",
        },
        {
            // "highlight": true,
            "img": "images/TCSVT2023_DisCoVQA.png",
            "title": "DisCoVQA: Temporal Distortion-Content Transformers for Video Quality Assessment",
            "authors": "Haoning Wu, Chaofeng Chen, Liang Liao, Jingwen Hou, Wenxiu Sun, Qiong Yan, Weisi Lin",
            "journal": "IEEE Transactions on Circuits and Systems for Video Technology (<b>TCSVT</b>)",
            "year": "2023",
            "arxiv": "https://arxiv.org/abs/2206.09853",
            "github": "https://github.com/QualityAssessment/DisCoVQA",
        },
        {
            // "highlight": true,
            "img": "images/TIP2021_FaceVideoInpaint.png",
            "title": "Deep Face Video Inpainting via UV Mapping",
            "authors": "Wenqi Yang, Zhenfang Chen, Chaofeng Chen, Guanying Chen, Kwan-Yee K. Wong",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2023,
            "arxiv": "https://arxiv.org/abs/2109.00681",
            "project": "https://ywq.github.io/FVIP/",
        },
        {
            "highlight": true,
            "img": "images/TIP2020_SPARNet.png",
            "title": "Learning Spatial Attention for Face Super-Resolution",
            "authors": "Chaofeng Chen, Dihong Gong, Hao Wang, Zhifeng Li, Kwan-Yee K. Wong",
            "journal": "IEEE Transactions on Image Processing (<b>TIP</b>)",
            "year": 2020,
            "arxiv": "https://arxiv.org/abs/2012.01211",
            "github": "https://github.com/chaofengc/Face-SPARNet",
        }
    ],
    "fields":
    {
        "arxiv": "arxiv",
        "pdf": "PDF",
        "github": "Github",
    },
    "author_links":
    {
        "Kwan-Yee K. Wong": "http://www.cs.hku.hk/~kykwong",
        "Liang Liao": "https://liaoliang92.github.io/homepage/",
        "Xiaoming Li": "https://csxmli2016.github.io/",
        "Haoning Wu": "http://teowu.github.io/",
        "Weisi Lin": "https://personal.ntu.edu.sg/wslin/Home.html",
        "Lei Zhang": "http://www4.comp.polyu.edu.hk/~cslzhang/",
        "Guanying Chen": "https://guanyingc.github.io/",
        "Zhenfang Chen": "http://zfchenunique.github.io/",
        "Wenqi Yang": "https://ywq.github.io/",
        "Wangmeng Zuo": "http://homepage.hit.edu.cn/wangmengzuo",
        "Shangchen Zhou": "https://shangchenzhou.com/",
        "Lingbo Yang": "http://lotayou.github.io/",
        "Xiaoguang Han": "https://mypage.cuhk.edu.cn/academics/hanxiaoguang/",
        "Chunyi Li": "http://lcysyzxdxc.github.io/",
        "Guangtao Zhai": "https://faculty.sjtu.edu.cn/zhaiguangtao/en/index.htm",
        "Zicheng Zhang": "https://github.com/zzc-1998",
        "Yipeng Qin": "https://www.cardiff.ac.uk/people/view/1508897-qin-yipeng",
        "Jinwei Gu": "http://www.gujinwei.org/",
        "Yuming Fang": "https://sites.google.com/site/leofangyuming/",
        "Shaozheng Hao": "https://haoosz.github.io/",
        "Mengcheng Lan": "https://mc-lan.github.io/",
        "Wenxiu Sun": "http://wenxiusun.com/",
        "Weixia Zhang": "https://sites.google.com/view/r-panda",
        "Yixuan Gao": "https://github.com/YixuanGao98",
        "Annan Wang": "https://github.com/AnnanWangDaniel",
        "Erli Zhang": "https://github.com/ZhangErliCarl/",
        "Qiong Yan": "https://scholar.google.com/citations?user=uT9CtPYAAAAJ&hl=en",
        "Xiongkuo Min": "https://sites.google.com/site/minxiongkuo/",
        "Jingwen Hou": "https://scholar.google.com.sg/citations?user=NlNOyiQAAAAJ&hl=zh-CN",
        "Tao Yang": "https://github.com/yangxy",
        "Shihui Guo": "https://scholar.google.co.uk/citations?user=RPAVxiAAAAAJ&hl=en",
        "Xinyu Shi": "https://xinyu-shi.github.io/",
    }
};